/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RefCodeRouteImport } from './routes/ref.$code'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedPontoRouteImport } from './routes/_authenticated/ponto'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedEditarIdRouteImport } from './routes/_authenticated/editar.$id'
import { Route as AuthenticatedAdminGamificacaoRouteImport } from './routes/_authenticated/admin/gamificacao'
import { Route as AuthenticatedAdminUsuariosIndexRouteImport } from './routes/_authenticated/admin/usuarios.index'
import { Route as AuthenticatedAdminSuporteIndexRouteImport } from './routes/_authenticated/admin/suporte.index'
import { Route as AuthenticatedAdminRelatoriosIndexRouteImport } from './routes/_authenticated/admin/relatorios.index'
import { Route as AuthenticatedAdminRegistrosIndexRouteImport } from './routes/_authenticated/admin/registros.index'
import { Route as AuthenticatedAdminPremiumIndexRouteImport } from './routes/_authenticated/admin/premium.index'
import { Route as AuthenticatedAdminFinanceiroIndexRouteImport } from './routes/_authenticated/admin/financeiro.index'
import { Route as AuthenticatedAdminEmpresasIndexRouteImport } from './routes/_authenticated/admin/empresas.index'
import { Route as AuthenticatedAdminConfigIndexRouteImport } from './routes/_authenticated/admin/config.index'
import { Route as AuthenticatedAdminUsuariosIdRouteImport } from './routes/_authenticated/admin/usuarios.$id'
import { Route as AuthenticatedAdminEmpresasNovaRouteImport } from './routes/_authenticated/admin/empresas.nova'
import { Route as AuthenticatedAdminEmpresasIdRouteImport } from './routes/_authenticated/admin/empresas.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RefCodeRoute = RefCodeRouteImport.update({
  id: '/ref/$code',
  path: '/ref/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPontoRoute = AuthenticatedPontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedEditarIdRoute = AuthenticatedEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminGamificacaoRoute =
  AuthenticatedAdminGamificacaoRouteImport.update({
    id: '/gamificacao',
    path: '/gamificacao',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosIndexRoute =
  AuthenticatedAdminUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSuporteIndexRoute =
  AuthenticatedAdminSuporteIndexRouteImport.update({
    id: '/suporte/',
    path: '/suporte/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRelatoriosIndexRoute =
  AuthenticatedAdminRelatoriosIndexRouteImport.update({
    id: '/relatorios/',
    path: '/relatorios/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRegistrosIndexRoute =
  AuthenticatedAdminRegistrosIndexRouteImport.update({
    id: '/registros/',
    path: '/registros/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPremiumIndexRoute =
  AuthenticatedAdminPremiumIndexRouteImport.update({
    id: '/premium/',
    path: '/premium/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceiroIndexRoute =
  AuthenticatedAdminFinanceiroIndexRouteImport.update({
    id: '/financeiro/',
    path: '/financeiro/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmpresasIndexRoute =
  AuthenticatedAdminEmpresasIndexRouteImport.update({
    id: '/empresas/',
    path: '/empresas/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfigIndexRoute =
  AuthenticatedAdminConfigIndexRouteImport.update({
    id: '/config/',
    path: '/config/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosIdRoute =
  AuthenticatedAdminUsuariosIdRouteImport.update({
    id: '/usuarios/$id',
    path: '/usuarios/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmpresasNovaRoute =
  AuthenticatedAdminEmpresasNovaRouteImport.update({
    id: '/empresas/nova',
    path: '/empresas/nova',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmpresasIdRoute =
  AuthenticatedAdminEmpresasIdRouteImport.update({
    id: '/empresas/$id',
    path: '/empresas/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/ponto': typeof AuthenticatedPontoRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/ref/$code': typeof RefCodeRoute
  '/admin/gamificacao': typeof AuthenticatedAdminGamificacaoRoute
  '/editar/$id': typeof AuthenticatedEditarIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/empresas/$id': typeof AuthenticatedAdminEmpresasIdRoute
  '/admin/empresas/nova': typeof AuthenticatedAdminEmpresasNovaRoute
  '/admin/usuarios/$id': typeof AuthenticatedAdminUsuariosIdRoute
  '/admin/config/': typeof AuthenticatedAdminConfigIndexRoute
  '/admin/empresas/': typeof AuthenticatedAdminEmpresasIndexRoute
  '/admin/financeiro/': typeof AuthenticatedAdminFinanceiroIndexRoute
  '/admin/premium/': typeof AuthenticatedAdminPremiumIndexRoute
  '/admin/registros/': typeof AuthenticatedAdminRegistrosIndexRoute
  '/admin/relatorios/': typeof AuthenticatedAdminRelatoriosIndexRoute
  '/admin/suporte/': typeof AuthenticatedAdminSuporteIndexRoute
  '/admin/usuarios/': typeof AuthenticatedAdminUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/ponto': typeof AuthenticatedPontoRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/ref/$code': typeof RefCodeRoute
  '/admin/gamificacao': typeof AuthenticatedAdminGamificacaoRoute
  '/editar/$id': typeof AuthenticatedEditarIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/empresas/$id': typeof AuthenticatedAdminEmpresasIdRoute
  '/admin/empresas/nova': typeof AuthenticatedAdminEmpresasNovaRoute
  '/admin/usuarios/$id': typeof AuthenticatedAdminUsuariosIdRoute
  '/admin/config': typeof AuthenticatedAdminConfigIndexRoute
  '/admin/empresas': typeof AuthenticatedAdminEmpresasIndexRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroIndexRoute
  '/admin/premium': typeof AuthenticatedAdminPremiumIndexRoute
  '/admin/registros': typeof AuthenticatedAdminRegistrosIndexRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosIndexRoute
  '/admin/suporte': typeof AuthenticatedAdminSuporteIndexRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/ponto': typeof AuthenticatedPontoRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/ref/$code': typeof RefCodeRoute
  '/_authenticated/admin/gamificacao': typeof AuthenticatedAdminGamificacaoRoute
  '/_authenticated/editar/$id': typeof AuthenticatedEditarIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/empresas/$id': typeof AuthenticatedAdminEmpresasIdRoute
  '/_authenticated/admin/empresas/nova': typeof AuthenticatedAdminEmpresasNovaRoute
  '/_authenticated/admin/usuarios/$id': typeof AuthenticatedAdminUsuariosIdRoute
  '/_authenticated/admin/config/': typeof AuthenticatedAdminConfigIndexRoute
  '/_authenticated/admin/empresas/': typeof AuthenticatedAdminEmpresasIndexRoute
  '/_authenticated/admin/financeiro/': typeof AuthenticatedAdminFinanceiroIndexRoute
  '/_authenticated/admin/premium/': typeof AuthenticatedAdminPremiumIndexRoute
  '/_authenticated/admin/registros/': typeof AuthenticatedAdminRegistrosIndexRoute
  '/_authenticated/admin/relatorios/': typeof AuthenticatedAdminRelatoriosIndexRoute
  '/_authenticated/admin/suporte/': typeof AuthenticatedAdminSuporteIndexRoute
  '/_authenticated/admin/usuarios/': typeof AuthenticatedAdminUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/configuracoes'
    | '/historico'
    | '/ponto'
    | '/relatorio'
    | '/ref/$code'
    | '/admin/gamificacao'
    | '/editar/$id'
    | '/admin/'
    | '/admin/empresas/$id'
    | '/admin/empresas/nova'
    | '/admin/usuarios/$id'
    | '/admin/config/'
    | '/admin/empresas/'
    | '/admin/financeiro/'
    | '/admin/premium/'
    | '/admin/registros/'
    | '/admin/relatorios/'
    | '/admin/suporte/'
    | '/admin/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/configuracoes'
    | '/historico'
    | '/ponto'
    | '/relatorio'
    | '/ref/$code'
    | '/admin/gamificacao'
    | '/editar/$id'
    | '/admin'
    | '/admin/empresas/$id'
    | '/admin/empresas/nova'
    | '/admin/usuarios/$id'
    | '/admin/config'
    | '/admin/empresas'
    | '/admin/financeiro'
    | '/admin/premium'
    | '/admin/registros'
    | '/admin/relatorios'
    | '/admin/suporte'
    | '/admin/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/configuracoes'
    | '/_authenticated/historico'
    | '/_authenticated/ponto'
    | '/_authenticated/relatorio'
    | '/ref/$code'
    | '/_authenticated/admin/gamificacao'
    | '/_authenticated/editar/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/empresas/$id'
    | '/_authenticated/admin/empresas/nova'
    | '/_authenticated/admin/usuarios/$id'
    | '/_authenticated/admin/config/'
    | '/_authenticated/admin/empresas/'
    | '/_authenticated/admin/financeiro/'
    | '/_authenticated/admin/premium/'
    | '/_authenticated/admin/registros/'
    | '/_authenticated/admin/relatorios/'
    | '/_authenticated/admin/suporte/'
    | '/_authenticated/admin/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RefCodeRoute: typeof RefCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ref/$code': {
      id: '/ref/$code'
      path: '/ref/$code'
      fullPath: '/ref/$code'
      preLoaderRoute: typeof RefCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ponto': {
      id: '/_authenticated/ponto'
      path: '/ponto'
      fullPath: '/ponto'
      preLoaderRoute: typeof AuthenticatedPontoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/editar/$id': {
      id: '/_authenticated/editar/$id'
      path: '/editar/$id'
      fullPath: '/editar/$id'
      preLoaderRoute: typeof AuthenticatedEditarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/gamificacao': {
      id: '/_authenticated/admin/gamificacao'
      path: '/gamificacao'
      fullPath: '/admin/gamificacao'
      preLoaderRoute: typeof AuthenticatedAdminGamificacaoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios/': {
      id: '/_authenticated/admin/usuarios/'
      path: '/usuarios'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/suporte/': {
      id: '/_authenticated/admin/suporte/'
      path: '/suporte'
      fullPath: '/admin/suporte/'
      preLoaderRoute: typeof AuthenticatedAdminSuporteIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/relatorios/': {
      id: '/_authenticated/admin/relatorios/'
      path: '/relatorios'
      fullPath: '/admin/relatorios/'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/registros/': {
      id: '/_authenticated/admin/registros/'
      path: '/registros'
      fullPath: '/admin/registros/'
      preLoaderRoute: typeof AuthenticatedAdminRegistrosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/premium/': {
      id: '/_authenticated/admin/premium/'
      path: '/premium'
      fullPath: '/admin/premium/'
      preLoaderRoute: typeof AuthenticatedAdminPremiumIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financeiro/': {
      id: '/_authenticated/admin/financeiro/'
      path: '/financeiro'
      fullPath: '/admin/financeiro/'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/empresas/': {
      id: '/_authenticated/admin/empresas/'
      path: '/empresas'
      fullPath: '/admin/empresas/'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/config/': {
      id: '/_authenticated/admin/config/'
      path: '/config'
      fullPath: '/admin/config/'
      preLoaderRoute: typeof AuthenticatedAdminConfigIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios/$id': {
      id: '/_authenticated/admin/usuarios/$id'
      path: '/usuarios/$id'
      fullPath: '/admin/usuarios/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/empresas/nova': {
      id: '/_authenticated/admin/empresas/nova'
      path: '/empresas/nova'
      fullPath: '/admin/empresas/nova'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasNovaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/empresas/$id': {
      id: '/_authenticated/admin/empresas/$id'
      path: '/empresas/$id'
      fullPath: '/admin/empresas/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmpresasIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminGamificacaoRoute: typeof AuthenticatedAdminGamificacaoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEmpresasIdRoute: typeof AuthenticatedAdminEmpresasIdRoute
  AuthenticatedAdminEmpresasNovaRoute: typeof AuthenticatedAdminEmpresasNovaRoute
  AuthenticatedAdminUsuariosIdRoute: typeof AuthenticatedAdminUsuariosIdRoute
  AuthenticatedAdminConfigIndexRoute: typeof AuthenticatedAdminConfigIndexRoute
  AuthenticatedAdminEmpresasIndexRoute: typeof AuthenticatedAdminEmpresasIndexRoute
  AuthenticatedAdminFinanceiroIndexRoute: typeof AuthenticatedAdminFinanceiroIndexRoute
  AuthenticatedAdminPremiumIndexRoute: typeof AuthenticatedAdminPremiumIndexRoute
  AuthenticatedAdminRegistrosIndexRoute: typeof AuthenticatedAdminRegistrosIndexRoute
  AuthenticatedAdminRelatoriosIndexRoute: typeof AuthenticatedAdminRelatoriosIndexRoute
  AuthenticatedAdminSuporteIndexRoute: typeof AuthenticatedAdminSuporteIndexRoute
  AuthenticatedAdminUsuariosIndexRoute: typeof AuthenticatedAdminUsuariosIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminGamificacaoRoute: AuthenticatedAdminGamificacaoRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminEmpresasIdRoute: AuthenticatedAdminEmpresasIdRoute,
    AuthenticatedAdminEmpresasNovaRoute: AuthenticatedAdminEmpresasNovaRoute,
    AuthenticatedAdminUsuariosIdRoute: AuthenticatedAdminUsuariosIdRoute,
    AuthenticatedAdminConfigIndexRoute: AuthenticatedAdminConfigIndexRoute,
    AuthenticatedAdminEmpresasIndexRoute: AuthenticatedAdminEmpresasIndexRoute,
    AuthenticatedAdminFinanceiroIndexRoute:
      AuthenticatedAdminFinanceiroIndexRoute,
    AuthenticatedAdminPremiumIndexRoute: AuthenticatedAdminPremiumIndexRoute,
    AuthenticatedAdminRegistrosIndexRoute:
      AuthenticatedAdminRegistrosIndexRoute,
    AuthenticatedAdminRelatoriosIndexRoute:
      AuthenticatedAdminRelatoriosIndexRoute,
    AuthenticatedAdminSuporteIndexRoute: AuthenticatedAdminSuporteIndexRoute,
    AuthenticatedAdminUsuariosIndexRoute: AuthenticatedAdminUsuariosIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedPontoRoute: typeof AuthenticatedPontoRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedEditarIdRoute: typeof AuthenticatedEditarIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedPontoRoute: AuthenticatedPontoRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedEditarIdRoute: AuthenticatedEditarIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RefCodeRoute: RefCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
